export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  clickhouseUrl: process.env.CLICKHOUSE_URL ?? "",
  clickhouseUser: process.env.CLICKHOUSE_USER ?? "default",
  clickhousePassword: process.env.CLICKHOUSE_PASSWORD ?? "",
  clickhouseDatabase: process.env.CLICKHOUSE_DATABASE ?? "default",
  clickhouseLogging: (process.env.CLICKHOUSE_LOGGING ?? "true") === "true",
};
